services:
  h2:
    image: buildo/h2database
    container_name: h2-db
    ports:
      - "1521:1521"  # H2 TCP
      - "8082:81"    # Web console
    environment:
      - H2_OPTIONS=-tcp -tcpAllowOthers -web -webAllowOthers -ifNotExists

  django:
    build: .
    container_name: django-app
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - h2